apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: yslllx7r9-java-quarkus-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/yslllx7r9-java-quarkus